### ISSUE TITLE
Fail to test and export the demo due to failing gradle build

### ISSUE THREAD

**Issue by golddotasksquestions** [funabab/godot-camera-plugin-demo#4]
Hi! First of thanks for sharing your camera plugin! I have waited for an opportunity to make use of it in my projects because I think it's pretty awesome, I always wanted to use the Camera in a Godot project and I'm really happy we have this plugin and demo available! 
Finally it is the time here, but I can't even get the demo to run.

I believe I have followed all necessary steps:

- I'm running Godot 3.3.4 (3.2 or later),
- I have set up the [Custom Build Environment](https://docs.godotengine.org/en/stable/getting_started/workflow/export/android_custom_build.html),
- I have enabled "Use Custom Build" in the Export settings,
- also in the Export settings I have set all keystore variables (and they are of course also set in the Editor Settings from other android projects),
- also in the Export settings I have enabled the "Camera" permission.
- I have checked the "Godot Camera Plugin" by funabab is enabled.

Is there anything missing?

This is the build message I get whenever I try to export or click the "fast deploy" icon:

```
> Task :preBuild UP-TO-DATE
> Task :preDebugBuild UP-TO-DATE
> Task :compileDebugAidl NO-SOURCE
> Task :compileDebugRenderscript NO-SOURCE
> Task :generateDebugBuildConfig UP-TO-DATE
> Task :javaPreCompileDebug UP-TO-DATE
> Task :checkDebugAarMetadata UP-TO-DATE
> Task :generateDebugResValues UP-TO-DATE
> Task :generateDebugResources UP-TO-DATE
> Task :mergeDebugResources UP-TO-DATE
> Task :createDebugCompatibleScreenManifests UP-TO-DATE
> Task :extractDeepLinksDebug UP-TO-DATE
> Task :processDebugMainManifest UP-TO-DATE
> Task :processDebugManifest UP-TO-DATE
> Task :processDebugManifestForPackage UP-TO-DATE
> Task :processDebugResources UP-TO-DATE

> Task :compileDebugJavaWithJavac FAILED
C:\Users\ my user path...\camera-plugin-demo-master\android\godot-camera-plugin.funabab\src\org\godotengine\godot\funabab\camera

\FunababCameraPlugin.java:48: error: incompatible types: Godot cannot be converted to Context
                    godotCameraView = GodotCameraView.initializeView(mActivity, ParameterSerializer.unSerialize(parameters),
                                                                     ^
C:\Users\ my user path...\camera-plugin-demo-master\android\godot-camera-plugin.funabab\src\org\godotengine\godot\funabab\camera

\FunababCameraPlugin.java:57: error: cannot find symbol
                mRoot = (ViewGroup) mActivity.layout.getParent();
                                             ^
  symbol:   variable layout
  location: variable mActivity of type Godot
C:\Users\ my user path...\camera-plugin-demo-master\android\godot-camera-plugin.funabab\src\org\godotengine\godot\funabab\camera

\FunababCameraPlugin.java:255: error: incompatible types: Activity cannot be converted to Godot
        mActivity = (Godot) p_activity;
                            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get 

full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
12 actionable tasks: 1 executed, 11 up-to-date

Exit Code: 1
```

**Comment by Swaraj-cs** [comment]
Any option to work with 3.3.2 ? Or any other suggestions
